apiVersion: apps/v1
kind: Deployment
metadata:
  name: movies
spec:
  selector:
    matchLabels:
      app: movies
  template:
    metadata:
      labels:
        app: movies
    spec:
      containers:
        - name: movies
          image: vncsprd/rotten-potatoes:v2
          ports:
            - containerPort: 5000
          env:
            - name: MONGODB_DB
              value: admin
            - name: MONGODB_HOST
              value: mongo-service
            - name: MONGODB_PORT
              value: "27017"
            - name: MONGODB_USERNAME
              value: mongouser
            - name: MONGODB_PASSWORD
              value: mongopwd
