apiVersion: v1
kind: Service
metadata:
  name: movies-service
spec:
  selector:
    app: movies
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30000 #porta definida na criação do cluster k3d
  type: NodePort
